version: '3.3'
services:
    gitlab:
      # image: 'twang2218/gitlab-ce-zh:11.1.4'
      image: 'gitlab/gitlab-ce:12.4.1-ce.0'
      container_name: "gitlab"
      restart: unless-stopped
      privileged: true
      hostname: 'gitlab.l2xy.com'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url ${GITLAB_EXTERNAL_URL}
          gitlab_rails['time_zone'] = ${GITLAB_RAILS_TIME_ZONE}
          gitlab_rails['smtp_enable'] = ${GITLAB_RAILS_SMTP_ENABLE}
          gitlab_rails['smtp_address'] = ${GITLAB_RAILS_SMTP_ADDRESS}
          gitlab_rails['smtp_port'] = ${GITLAB_RAILS_SMTP_PORT}
          gitlab_rails['smtp_user_name'] = ${GITLAB_RAILS_SMTP_USER_NAME}
          gitlab_rails['smtp_password'] = ${GITLAB_RAILS_SMTP_PASSWORD}
          gitlab_rails['smtp_authentication'] = ${GITLAB_RAILS_SMTP_AUTHENTICATION}
          gitlab_rails['smtp_enable_starttls_auto'] = ${GITLAB_RAILS_SMTP_ENABLE_STARTTLS_AUTO}
          gitlab_rails['smtp_tls'] = ${GITLAB_RAILS_SMTP_TLS}
          gitlab_rails['gitlab_email_from'] = ${GITLAB_RAILS_GITLAB_EMAIL_FROM}
          gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_RAILS_GITLAB_SHELL_SSH_PORT}
          unicorn['enable'] = ${UNICORN_ENABLE}
          unicorn['worker_processes'] = ${UNICORN_WORKER_PROCESSES}
          unicorn['worker_timeout'] = ${UNICORN_WORKER_TIMEOUT}
          unicorn['worker_memory_limit_max'] = ${UNICORN_WORKER_MEMORY_LIMIT_MAX}
          unicorn['worker_memory_limit_min'] = ${UNICORN_WORKER_MEMORY_LIMIT_MIN}
          sidekiq['concurrency'] = ${SIDEKIQ_CONCURRENCY}
          postgresql['shared_buffers'] = ${POSTGRESQL_SHARED_BUFFERS}
          postgresql['max_worker_processes'] = ${POSTGRESQL_MAX_WORKER_PROCESSES}
      ports:
        - '${GITLAB_DOMAIN_PORT}:80'
        - '${GITLAB_NGINX_PORT}:22'
      volumes:
        - ${GITLAB_CONFIG_DIR}:/etc/gitlab
        - ${GITLAB_DATA_DIR}:/var/opt/gitlab
        - ${GITLAB_LOGS_DIR}:/var/log/gitlab
        - /etc/localtime:/etc/localtime